theme: jekyll-theme-cayman
title: Machine Intelligence for Good
description: Welcome to Max Thapa's homepage. I am a graduate of theoretical physics turned artificial intelligence enthusiast. Here you can see my projects and work in the pursuit of understanding machine learning and how it can beneft society.
